### ISSUE TITLE
Button elements..

### ISSUE THREAD

**Issue by gosoccerboy5** [MystPi/dreamcss#1]
The little transition from non-hover to hover is pretty neat, but it doesn't suggest interactivity that much. I propose either making it use `cursor: pointer;` for the `button` rule or `background-color: /* insert some color or CSS variable here */;` for the `button:hover` rule.

**Comment by MystPi** [comment]
Great idea! This will be added.

**Comment by MystPi** [comment]
I implemented `cursor: pointer`, thanks for the tip!

**Comment by gosoccerboy5** [comment]
Alright thanks
